### ISSUE TITLE
ETL for new batch of data to anntate

### ISSUE THREAD

**Issue by keighrim** [clamsproject/aapb-annenv-role-filler-binder#13]
Since the smaller batch compiled form https://github.com/clamsproject/aapb-annenv-role-filler-binder/issues/11 is now all annotated by multiple annotators, we'd like to process more videos for next rounds of annotation. 

The batch we're going to use will be compiled from https://github.com/clamsproject/aapb-annotations/issues/44. Then the ETL process will be something like this; 

1. run existing "swt" detection apps on the data batch
    * https://apps.clams.ai/slatedetection/v2.1/
    * https://apps.clams.ai/chyron-detection/v1.0/
    * https://github.com/clamsproject/app-fewshotclassifier/tree/credits
1. run [frame extractor](https://github.com/clamsproject/aapb-annenv-role-filler-binder/blob/7d2704b1298cde1ed715e506e91c7a27efb82fff/extract_frames.py) with output MMIF. At the moment the extracted image files are thrown into one directory. But we need to think about how we want to tag the image files based on the `TimeFrame` type they are belong to. (changing the file naming scheme to include such tags might affect how the annenv access those image files in a pretty huge way, so that's probably not the best idea)
https://github.com/clamsproject/aapb-annenv-role-filler-binder/blob/7d2704b1298cde1ed715e506e91c7a27efb82fff/extract_frames.py#L33
https://github.com/clamsproject/aapb-annenv-role-filler-binder/blob/7d2704b1298cde1ed715e506e91c7a27efb82fff/main.py#L26-L48
1. run [ocr](https://github.com/clamsproject/aapb-annenv-role-filler-binder/blob/7d2704b1298cde1ed715e506e91c7a27efb82fff/ocr.py) on the extracted images. The script will use easyocr library and heavily rely GPU computation.

**Comment by keighrim** [comment]
credits detection + OCR on 51 videos in this new batch is ready now in child server. @jarumihooi I remember you said you wanted to use a subset of the batch as a new "validation?" set. Regarding that, 
1. Do you have a particular set of GUID in mind, or should I randomly sample some (say, 5 videos or ~10%) of them?
2. Are you going to be the second annotator for the subset? 
3. Do you want me to spin up two pairs of tool instances for each annotator (total 4 instances, assuming 2 annotators); one for the subset, and another for the rest? Or you want to keep just one environment with all 51 videos, but prioritizing the "subset" GUIDs first?

**Comment by jarumihooi** [comment]
Hi Keigh, about 200-250 frames I think is enough for the validation set. 
I can be for the validation set, but I think its actually even better to have the other annotator/RA be a part of it as well (once they are practiced/onboarded. No more onboarding using the validation set. )

It doesnt matter too much. If we simply say verbally that the validation set in the first x videos that works fine.

**Comment by keighrim** [comment]
I re-trained fewshot app with [this quick annotation of mine _only with credits_](https://github.com/clamsproject/app-fewshotclassifier/blob/4f4083652a3206fdacfc3db59adad6f9c9e99bd4/credits2.csv) and ran the "ET"L pipeline with the `credits2` fewshot app index. 
Here are the numbers of extracted frames 
``` bash

**Comment by keighrim** [comment]
closing this as no additional data ingestion is planned.
